{% set name = "sphinx-wagtail-theme" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_wagtail_theme-{{ version }}.tar.gz
  sha256: 94e3296226b6607af19d804b305e3912aff4ec5aaacee23c78c2d6dc18f5256a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - sphinx_wagtail_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail/sphinx_wagtail_theme
  summary: Sphinx Wagtail theme
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - xhochy
